services:
  external-api:
    build: ./service-a/app
    container_name: external-api
    depends_on:
      - redis-api
    networks:
      - app-network
    ports:
      - '8000:8000'
  redis:
    image: redis:latest
    container_name: redis
    # ports:
    #   - "6379:6379"
    networks:
      - app-network

  redis-api: 
    build: ./service-b/app
    container_name: redis-api
    depends_on:
      - redis
    networks:
      - app-network
    # ports:
    #   - '8080:8080'

networks:
  app-network:
    driver: bridge